# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9680285d9f590e990e72aa12b7667320151871a54329274bd6b21b8a2969b2e181d88fddc92e1fc06b6fafda5c26db449b2333f82293114fed39d2f581753d1e

test:
  secret_key_base: 07a045a2ef9adad4d699587b965c65d1612a6853f8e3134f36d6a07093834fa091353ad917083ba9a9e775a5fcbb79faec73db5d73c38333a432d74fcf4360d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
